import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link" 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "first project using Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ padding: "1rem", backgroundColor: "#f0f0f0" }}>
          <Link href={'/posts'} style={{marginRight: '80px'}}>go to posts</Link>
          <Link href={'/'}>
            <h1 style={{marginRight: '80px', display: 'inline'}}>Logo</h1>
          </Link>
      
          <Link href={'/articles'}>go to articles</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
